### PR TITLE
Fixed LoginForm validation.

### PR DESCRIPTION
**Pull request by radekmie**
This will work with uniforms@1.8.3.

### CODE REVIEW

**Comment by radekmie** [comment]
@cyclops24?

**Comment by cyclops24** [comment]
Hi @radekmie , 
Excuse me man. I have a little issue and can't access to internet some days, I'll check it right now.
Again excuse me brow for late response and very thanks for contribute.

**Comment by cyclops24** [comment]
@radekmie  Thanks man. It's fixed now. 😉

**Comment by radekmie** [comment]
@cyclops24 great!

**Pull request merged**
